# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package.json and package-lock.json first for caching dependencies
COPY package*.json ./

# Install dependencies without running scripts (we want to control the build)
RUN npm install --ignore-scripts

# Copy all the source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (if your server listens on a port, else remove)
# EXPOSE 3000

# Command to run the MCP server
CMD [ "npm", "start" ]
